package com.riffle.core.domain.comic.panel

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Panel-detector regression tests that run against real comic-page images.
 *
 * Every fixture is source-controlled in
 * `core/domain/src/jvmTest/resources/panel-detection-fixtures/` so tests always run on CI —
 * no conditional skips, no `.context/` paths.
 *
 * ## Fixture formats
 *
 * **Binarized mask PNG** (preferred, copyright-safe per ADR 0062): black pixels = content,
 * white pixels = gutter. Load with [loadMaskFixture], which maps black → DARK and white → LIGHT
 * and returns a [PixelGrid] ready for detection. Use this for images generated by the in-app
 * panel reporter (`PanelMaskEncoder`).
 *
 * **Raw page image**: a grayscale or colour scan. Load with [loadRawFixture] and pass the
 * returned [PixelGrid] to `detector.detect()`. Use only when the bug depends on real luma
 * values (e.g. background-estimation issues that a binarized mask can't reproduce).
 *
 * ## Adding a new test
 *  1. Download the binarized mask PNG from the issue's `panel-reports` branch URL and copy it
 *     to `core/domain/src/jvmTest/resources/panel-detection-fixtures/issue-<N>-<desc>.png`.
 *  2. Call [loadMaskFixture] (or [loadRawFixture] when luma fidelity is needed).
 *  3. Assert [PanelSource] and panel count; add geometry assertions where the issue specifies them.
 *  4. Run the test — it must fail RED before you touch [PanelDetector].
 *
 * Synthetic / geometry-only tests belong in [PanelDetectorTest].
 */
class PanelDetectorImageTest {

    private val detector = PanelDetector()

    @Test
    fun `scanned splash-plus-two-panels page is detected correctly`() {
        // Regression for page 56: full-width splash on top + two panels at the bottom.
        // Fixture is a binarized mask (black=content, white=gutter) generated from the
        // original scanned image — copyright-safe per ADR 0062.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-old-splash-plus-two-panels-p56.png")
        val result = detector.detect(grid, pageIndex = 56, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals("expected 3 panels for splash+2-panel layout", 3, result.panels.size)
        val topPanels = result.panels.filter { it.y + it.height / 2 < grid.height / 2 }
        val bottomPanels = result.panels.filter { it.y + it.height / 2 >= grid.height / 2 }
        assertEquals("1 splash panel in top half", 1, topPanels.size)
        assertEquals("2 panels in bottom half", 2, bottomPanels.size)
        assertTrue("splash is wide", topPanels[0].width >= grid.width * 0.6)
        val leftBottom = bottomPanels.filter { it.x + it.width / 2 < grid.width / 2 }
        val rightBottom = bottomPanels.filter { it.x + it.width / 2 >= grid.width / 2 }
        assertEquals("one panel in bottom-left quadrant", 1, leftBottom.size)
        assertEquals("one panel in bottom-right quadrant", 1, rightBottom.size)
    }

    @Test
    fun `scanned page with dark book-spine corners is detected correctly`() {
        // Regression for page 58: a 3x2 grid of 6 panels on a scanned comic page.
        // The scanner captured dark book-binding pixels in all 4 corners, dragging the
        // 8-sample median background estimate down to 142. At that value the tan page
        // gutter (luma ~200-215) reads as content (diff 58 >= 32 threshold), flooding
        // the entire page with "content" pixels and leaving no gutter for flood fill —
        // the single resulting CC covers the whole page and triggers Fallback.
        //
        // Fix: sample the full border at regular intervals and use the 85th percentile
        // instead of the median of 8 corner/midpoint samples. The left and right edges of
        // a scanned page are authentic paper margin; they represent ~60% of border samples.
        // The 85th percentile lands in the light range even when 40% of border samples are
        // dark spine/binding pixels, correctly estimating the tan paper background at ~208.
        //
        // Fixture is a binarized mask (black=content, white=gutter) — copyright-safe per ADR 0062.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-old-dark-spine-corners-p58.png")
        val result = detector.detect(grid, pageIndex = 58, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals("expected 6 panels for 3x2 grid", 6, result.panels.size)
        val topRow = result.panels.filter { it.y + it.height / 2 < grid.height / 2 }
        val bottomRow = result.panels.filter { it.y + it.height / 2 >= grid.height / 2 }
        assertEquals("3 panels in top row", 3, topRow.size)
        assertEquals("3 panels in bottom row", 3, bottomRow.size)
        fun assertThreeColumnsPresent(row: List<PanelRegion>, label: String) {
            val left = row.filter { it.x + it.width / 2 < grid.width / 3 }
            val centre = row.filter { it.x + it.width / 2 in grid.width / 3 until 2 * grid.width / 3 }
            val right = row.filter { it.x + it.width / 2 >= 2 * grid.width / 3 }
            assertEquals("$label: 1 panel in left third", 1, left.size)
            assertEquals("$label: 1 panel in centre third", 1, centre.size)
            assertEquals("$label: 1 panel in right third", 1, right.size)
        }
        assertThreeColumnsPresent(topRow, "top row")
        assertThreeColumnsPresent(bottomRow, "bottom row")
    }

    @Test
    fun `scanned page with caption-box at top of bottom-left panel is not cut off`() {
        // Regression for issue #751: page 66 with 1 top panel, 1 middle panel, 2 bottom panels
        // (left and right). The bottom-left panel has a light caption box whose left edge touches
        // the page border. Flood-fill gutter enters the caption interior via the border, making the
        // narrow white margin below the caption score ≥30% gutter pixels. splitSinglePanelRecursively
        // found that narrow strip (well under internalGutterMaxFraction), split the left panel into
        // a caption piece (top ~11% of page) and a character-art piece (bottom ~21%). The caption
        // piece fell below minPanelDimensionFraction (15%) and was dropped, leaving the bottom-left
        // panel starting at y=1239 instead of y=1070.
        // Uses raw fixture (not binarized mask) because the bug depends on real luma for background
        // estimation — the page has a dark scanned background that a binary mask cannot reproduce.
        val grid = loadRawFixture("panel-detection-fixtures/issue-751-page-66.png")
        val w = grid.width
        val h = grid.height
        val result = detector.detect(grid, pageIndex = 0, originalWidth = w, originalHeight = h)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 4 panels for 1-wide+1-wide+2-column layout, got ${result.panels.size} (source=${result.source})",
            4, result.panels.size,
        )
        // The two bottom panels must start at approximately the same y coordinate — the bottom-left
        // panel must not be cut off so that it starts much later than the bottom-right panel.
        val sortedByY = result.panels.sortedBy { it.y }
        val bottomTwo = sortedByY.takeLast(2)
        val minBottomY = bottomTwo.minOf { it.y }
        val maxBottomY = bottomTwo.maxOf { it.y }
        assertTrue(
            "both bottom panels must start at roughly the same y (within 5% of page height); " +
                "got y values=${bottomTwo.map { it.y }} with difference=${maxBottomY - minBottomY}, threshold=${(h * 0.05).toInt()}",
            maxBottomY - minBottomY < h * 0.05,
        )
    }

    @Test
    fun `noir page with wide banner panel between splash and three bottom panels is not missed`() {
        // Regression for issue #755: page 42. Top splash + full-width banner + bottom panels.
        // The banner (h ≈ 393px on a 3054px page = ~13%) was silently dropped by
        // applyGlobalSanityChecks because its height fell below minPanelDimensionFraction (15%).
        // Fix: panels with width ≥ 50% of the page and height ≥ 5% are kept as banners.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-755-missed-panel-p42.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        // 4 panels: top-left splash, top-right panel, wide banner strip, bottom section.
        // The column gutter between the two top panels is wide enough at full resolution
        // for the binarizer to keep it clean; the banner is kept by the banner exception.
        assertEquals(
            "expected 4 panels for splash+banner+bottom layout, got ${result.panels.size}; panels=${result.panels}",
            4, result.panels.size,
        )
        // The banner must appear: a very wide panel (≥ 75% page width) in the middle vertical
        // band of the page (not at the very top, not at the very bottom).
        val banners = result.panels.filter { p ->
            p.width.toDouble() / grid.width >= 0.75 &&
                p.y > grid.height * 0.25 &&
                p.y + p.height < grid.height * 0.90
        }
        assertEquals(
            "expected exactly one wide banner panel in the middle band; panels=${result.panels}",
            1, banners.size,
        )
    }

    @Test
    fun `bottom-row wide panel is not split in half by a compositional gap in the art`() {
        // Regression for issue #756: page 67. 2×2 panel grid above a full-width bottom panel.
        // splitAtInternalGutters found a false vertical gutter inside the bottom wide panel
        // (a low-content column in the art) and split it into two half-panels, so tapping
        // either half only zoomed to that fragment instead of the whole bottom scene.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-756-panel-cut-off-p67.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 5 panels for 2+2+1 layout, got ${result.panels.size} (source=${result.source})",
            5, result.panels.size,
        )
        // Bottom panel must span ≥ 60% of the page width.
        val bottomPanels = result.panels.filter { p -> p.y + p.height / 2 > grid.height * 2 / 3 }
        assertEquals("expected one wide bottom panel", 1, bottomPanels.size)
        assertTrue(
            "bottom panel must span ≥ 60% of page width; got w=${bottomPanels[0].width} on ${grid.width}px",
            bottomPanels[0].width.toDouble() / grid.width >= 0.6,
        )
    }

    @Test
    fun `right-side panels are not merged into one tall panel when separated by a narrow gutter`() {
        // Regression for issue #757: page 68. 2×2 layout (left column 2 panels, right column 2
        // panels) above a full-width bottom panel — 5 panels total. The right-column gutter is
        // enclosed by panel borders; flood-fill scores only ~1.5% (vs the 30% threshold) and the
        // detected flood-fill gutter is at the edge margin (rejected by min-dimension check). Fix:
        // projection-based fallback triggers when flood-fill produces no valid split, and splits on
        // the widest continuous run of low-content rows (h ≥ 7).
        val grid = loadMaskFixture("panel-detection-fixtures/issue-757-merged-panels-p68.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 5 panels for 2×2-above-banner layout, got ${result.panels.size} (source=${result.source})",
            5, result.panels.size,
        )
        // Both right-side stacked panels must sit in the top two-thirds of the page.
        val rightPanels = result.panels.filter { p -> p.x + p.width / 2 > grid.width / 2 }
        val rightTopHalf = rightPanels.filter { p -> p.y + p.height / 2 < grid.height * 2 / 3 }
        assertTrue(
            "expected ≥ 2 right-side panels in the top two-thirds; got all panels=${result.panels}, rightPanels=$rightPanels",
            rightTopHalf.size >= 2,
        )
    }

    @Test
    fun `right-side panels are not merged when left column is one tall panel`() {
        // Regression for issue #758: page 70. The right column has two stacked panels; the left
        // column appears as one tall panel in the binarized mask (the gutter between the two left
        // panels is not visible in the fixture). The right side must be correctly detected as two
        // separate panels despite the enclosed gutter — the projection-based fallback handles this.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-758-merged-panels-p70.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 4 panels (tall-left + 2-right-stacked + bottom), got ${result.panels.size} (source=${result.source})",
            4, result.panels.size,
        )
        // Both right-side stacked panels must sit in the top two-thirds of the page.
        val rightPanels = result.panels.filter { p -> p.x + p.width / 2 > grid.width / 2 }
        val rightTopSection = rightPanels.filter { p -> p.y + p.height / 2 < grid.height * 2 / 3 }
        assertTrue(
            "expected ≥ 2 right-side panels in the top two-thirds; got rightPanels=$rightPanels",
            rightTopSection.size >= 2,
        )
    }

    @Test
    fun `right-side stacked panels are detected when left column is one tall panel`() {
        // Regression for issue #759: page 74. Left column is one tall panel spanning rows 1+2
        // while the right column has two separate stacked panels. The projection found a row
        // boundary at the right-column gutter level and created a phantom full-width row band
        // (a known limitation); the right-column panels must still be correctly detected as two
        // separate stacked panels in the top two-thirds.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-759-split-panel-p74.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(
            "expected 5 panels for tall-left + 2-right-stacked + 2-bottom layout, got ${result.panels.size} (source=${result.source})",
            5, result.panels.size,
        )
        // The right column must be split into at least 2 panels (not merged into one tall panel).
        val rightPanels = result.panels.filter { p -> p.x + p.width / 2 > grid.width / 2 }
        assertTrue(
            "expected ≥ 2 right-side panels (right column was merged); got rightPanels=$rightPanels",
            rightPanels.size >= 2,
        )
    }

    @Test
    fun `lower-left tall slanted panel is not split at horizontal row boundary`() {
        // Regression for issue #767: page 24. The lower-left panel spans the lower two row bands,
        // but projection returned a 4-row x 2-column grid and split it into two separate panels.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-767-split-left-lower-panel-p24.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 7 panels with the lower-left tall panel merged, got ${result.panels.size}; panels=${result.panels}",
            7, result.panels.size,
        )
        val lowerLeftTallPanels = result.panels.filter { p ->
            p.x + p.width / 2 < grid.width / 2 &&
                p.y > grid.height * 0.45 &&
                p.height.toDouble() / grid.height >= 0.40
        }
        assertEquals(
            "expected one tall lower-left panel spanning the lower two row bands; panels=${result.panels}",
            1, lowerLeftTallPanels.size,
        )
    }

    @Test
    fun `second-row left slanted panel contains tap near right edge`() {
        // Regression for issue #766: page 22. The second row has two slanted panels, the third
        // row is one full-width panel, and the reported tap at (432, 422) must remain inside the
        // left second-row bbox.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-766-panel-cut-off-p22.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 7 panels for 2 + 2 + 1 + 2 layout, got ${result.panels.size}; panels=${result.panels}",
            7, result.panels.size,
        )
        val secondRowPanels = result.panels.filter { p ->
            p.y + p.height / 2 in (grid.height * 0.25).toInt()..(grid.height * 0.50).toInt()
        }
        assertEquals("expected second row to split into two panels; panels=${result.panels}", 2, secondRowPanels.size)
        assertTrue(
            "expected the left second-row panel to contain tap (432, 422); secondRowPanels=$secondRowPanels",
            secondRowPanels.any { p ->
                p.x + p.width / 2 < grid.width / 2 &&
                    432 in p.x until p.x + p.width &&
                    422 in p.y until p.y + p.height
            },
        )
        val thirdRowPanels = result.panels.filter { p ->
            p.width.toDouble() / grid.width >= 0.85 &&
                p.y + p.height / 2 in (grid.height * 0.50).toInt()..(grid.height * 0.75).toInt()
        }
        assertEquals(
            "expected third row to be one full-width panel; panels=${result.panels}",
            1, thirdRowPanels.size,
        )
    }

    @Test
    fun `tall left panel spanning two row bands is ordered before the stacked right panels`() {
        // Regression for issue #780: page 25. The page has a tall left panel that spans row-bands
        // 2 and 3 (rows 2+3), with an upper-right panel and a lower-right panel stacked on the
        // right. PanelOrderer grouped all three into one row band (because the tall panel's y-extent
        // overlaps both right panels) and then sorted by x, putting lower-right (x=446) before
        // upper-right (x=520). The correct reading order is tall-left → upper-right → lower-right.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-780-wrong-panel-order.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        val ordered = PanelOrderer().order(result.panels)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 7 panels for 2+tall-left-with-2-right-stacked+2 layout, got ${ordered.size} (source=${result.source})",
            7, ordered.size,
        )
        // Identify the tall-left panel: left of centre, height > 40% of page height.
        val tallLeft = ordered.firstOrNull { p ->
            p.x + p.width / 2 < grid.width / 2 &&
                p.height.toDouble() / grid.height >= 0.40
        }
        assertNotNull("expected one tall left panel spanning ≥40% of page height; ordered=$ordered", tallLeft)
        // The upper-right panel is right of centre and its vertical centre sits in the upper-middle
        // section (not in the top row — that's covered by the top-right panel).
        val upperRight = ordered.firstOrNull { p ->
            p.x + p.width / 2 >= grid.width / 2 &&
                p.y + p.height / 2 in (grid.height * 0.30).toInt()..(grid.height * 0.55).toInt()
        }
        assertNotNull("expected one upper-right panel; ordered=$ordered", upperRight)
        // The lower-right panel is right of centre and starts in the lower half.
        val lowerRight = ordered.firstOrNull { p ->
            p.x + p.width / 2 >= grid.width / 2 &&
                p.y >= grid.height * 0.40 &&
                p.y > (upperRight?.bottom ?: 0)
        }
        assertNotNull("expected one lower-right panel below upperRight; ordered=$ordered", lowerRight)
        val tallLeftIdx = ordered.indexOf(tallLeft)
        val upperRightIdx = ordered.indexOf(upperRight)
        val lowerRightIdx = ordered.indexOf(lowerRight)
        assertTrue(
            "reading order must be tall-left($tallLeftIdx) → upper-right($upperRightIdx) → lower-right($lowerRightIdx); ordered=$ordered",
            tallLeftIdx < upperRightIdx && upperRightIdx < lowerRightIdx,
        )
    }

    @Test
    fun `row three left panel is not cut off at its right edge`() {
        // Regression for issue #783: page 26. An 8-panel (4×2) page where the third-row left
        // panel has a slanted right boundary. The detector found the panel 78px too narrow:
        // width=358 instead of the expected ≥430. The right edge was being over-trimmed because
        // the diagonal panel border left sparse content columns near the right boundary.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-783-panel-cut-off.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertEquals(
            "expected 8 panels for 4×2 layout, got ${result.panels.size} (source=${result.source})",
            8, result.panels.size,
        )
        // The third-row left panel is in the lower half of the page (y roughly 50-75%), left of centre.
        val thirdRowLeft = result.panels.filter { p ->
            p.y + p.height / 2 in (grid.height * 0.48).toInt()..(grid.height * 0.75).toInt() &&
                p.x + p.width / 2 < grid.width / 2
        }
        assertEquals(
            "expected exactly one third-row left panel; panels=${result.panels}",
            1, thirdRowLeft.size,
        )
        val panel = thirdRowLeft[0]
        val minExpectedWidth = (grid.width * 0.40).toInt()
        assertTrue(
            "third-row left panel must be ≥ 40% of page width (≥$minExpectedWidth); got w=${panel.width} at x=${panel.x}; panels=${result.panels}",
            panel.width >= minExpectedWidth,
        )
    }

    @Test
    fun `tall left panel spanning rows one and two is not split at the horizontal row boundary`() {
        // Regression for issue #784: page 28. The page has a tall character on the left spanning
        // rows 1-2 with a diagonal right boundary. The binarized fixture routes through the projection
        // path; mergeDiagonalSpanningPanels (which fixes this for the real JPEG via the CC path when
        // the detector sees two separate left-column CCs) is separately covered by a synthetic test in
        // PanelDetectorTest. This test pins the fixture's projection-path output so a Fallback
        // regression or panel-count collapse would be caught immediately.
        val grid = loadMaskFixture("panel-detection-fixtures/issue-784-split-panel.png")
        val result = detector.detect(grid, pageIndex = 0, originalWidth = grid.width, originalHeight = grid.height)
        assertEquals(PanelSource.Auto, result.source)
        assertTrue(
            "fixture should produce ≥ 6 panels from the projection path; got ${result.panels.size}: ${result.panels}",
            result.panels.size >= 6,
        )
    }

    // --- Helpers ---

    private val LIGHT: Byte = 240.toByte()
    private val DARK: Byte = 20.toByte()

    /**
     * Load a binarized-mask fixture (black=content, white=gutter) from the jvmTest classpath
     * and return it as a [PixelGrid]. Fixtures are stored as copyright-safe lossless PNGs per
     * ADR 0062 — black pixels map to [DARK] (content), any non-black pixel maps to [LIGHT] (gutter).
     *
     * Throws loudly if the resource is missing so the test fails rather than silently skipping.
     */
    private fun loadMaskFixture(resourcePath: String): PixelGrid {
        val stream = javaClass.classLoader.getResourceAsStream(resourcePath)
            ?: error("Fixture not found on classpath: $resourcePath — ensure the file exists under core/domain/src/jvmTest/resources/")
        val img = stream.use { javax.imageio.ImageIO.read(it) }
            ?: error("Could not decode image at $resourcePath")
        val w = img.width
        val h = img.height
        val luma = ByteArray(w * h)
        for (y in 0 until h) {
            for (x in 0 until w) {
                luma[y * w + x] = if ((img.getRGB(x, y) and 0xFFFFFF) == 0) DARK else LIGHT
            }
        }
        return PixelGrid(w, h, luma)
    }

    /**
     * Load a raw (non-binarized) page image from the jvmTest classpath and convert it to a
     * luma [PixelGrid] using BT.601 coefficients. Use when the bug depends on real luma values
     * (e.g. background-estimation failures) that a binarized mask cannot reproduce.
     */
    private fun loadRawFixture(resourcePath: String): PixelGrid {
        val stream = javaClass.classLoader.getResourceAsStream(resourcePath)
            ?: error("Fixture not found on classpath: $resourcePath — ensure the file exists under core/domain/src/jvmTest/resources/")
        val img = stream.use { javax.imageio.ImageIO.read(it) }
            ?: error("Could not decode image at $resourcePath")
        val w = img.width
        val h = img.height
        val luma = ByteArray(w * h)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val rgb = img.getRGB(x, y)
                val r = (rgb shr 16) and 0xFF
                val g = (rgb shr 8) and 0xFF
                val b = rgb and 0xFF
                luma[y * w + x] = (0.299 * r + 0.587 * g + 0.114 * b).toInt().coerceIn(0, 255).toByte()
            }
        }
        return PixelGrid(w, h, luma)
    }
}
